jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v5
            - run: uv venv
            - run: uv pip install mkdocs
            - run: .venv/bin/mkdocs gh-deploy

on:
    workflow_dispatch:
    push:
        branches:
            - main
