jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v5
            - run: uv venv
            - run: uv pip install mkdocs
            - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com' && .venv/bin/mkdocs gh-deploy

on:
    workflow_dispatch:
    push:
        branches:
            - main
